apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: q7goeef5r-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: q7goeef5r-go 
  name: q7goeef5r-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: q7goeef5r-go 
